name: Build Panasonic Aquarea

on:
  pull_request:
    paths:
      - "**/*aquarea*/**"
      - "**/*aquarea*"
  workflow_dispatch:

jobs:
  build:
    name: Build panasonic_aquarea (${{ matrix.variant }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant:
          - esp32
          - esp32s3
          - esp32c3
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Build firmware
        id: esphome_build
        uses: esphome/build-action@v8.1.0
        with:
          yaml-file: tests/panasonic_aquarea.yaml
          version: "2026.8.2"
          substitutions: |
            variant=${{ matrix.variant }}
